spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ref-project
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:ref-project
  jpa:
    hibernate:
      ddl-auto: create
