name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Grant execution permission for gradlew
        run: chmod +x gradlew
      - name: Test
        run: SPRING_PROFILES_ACTIVE=test ./gradlew test

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ref-backend .
          docker tag ref-backend naraekn/ref-backend:${GITHUB_SHA::7}
          docker push naraekn/ref-backend:${GITHUB_SHA::7}

